### DISCUSSION TITLE
AWS issues

### DISCUSSION THREAD

**Discussion by Blackbam** [php-amqplib/RabbitMqBundle#640] [Q&A]
AWS does only support AMQPS. Locally the bundle seems to work even with AMQPS without issues. But in AWS we are still getting exceptions for exactly the same implementation.

This is our config.yml (AWS docker):

```
old_sound_rabbit_mq:
    connections:
        secure:
            url: 'amqps://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASSWORD)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%'
            vhost: '%env(RABBITMQ_VHOST)%'
            lazy: true
            connection_timeout: 6
            read_write_timeout: 6
            ssl_context:
                verify_peer: false
            keepalive: true
            heartbeat: 60
            use_socket: true # default false
            
    producers:
        # use 'old_sound_rabbit_mq.[my-producer-name]_producer' service to send data.
        article_create:
            connection: secure
            exchange_options: { name: pimcore.article.create, type: topic }
            queue_options:
                name: article_create
```

Without sockets: `Broken pipe or closed connection`

With sockets: ```[2021-06-08 15:59:45] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: socket_recv(): unable to read from socket [104]: Connection reset by peer" at /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php line 121 {"exception":"[object] (ErrorException(code: 0): Warning: socket_recv(): unable to read from socket [104]: Connection reset by peer at /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/SocketIO.php:121)"} []```

Has anybody experience on how to run this bundle in AWS properly? Maybe its a simple configuration issue but we really tried a lot. All environment variables should be correctly set. We use the URL in the configuration because we did not find another way to set AMQPS in the bundle.
