### ISSUE TITLE
one producer, one exchange, multiple queues

### ISSUE THREAD

**Issue by ryanalbon** [php-amqplib/RabbitMqBundle#121]
Hi there,

I'm having trouble understanding how to bind multiple queues to one exchange via a single producer. I understand that I can bind a single queue to an exchange with a configuration that looks like this:

```
producers:
    producer_1:
        connection: default
        exchange_options: {name: 'exchange_1', type: direct}
        queue_options: {name: 'queue_1', routing_keys: ['key_1']}
```

The above will configure a producer called "producer_1" which publishes to "exchange_1", and binds "exchange_1" to "queue_1" via "key_1".

I'd like to use the same producer to bind multiple queues to one exchange via different routing keys. I was hoping something like the following would work:

```
producers:
    producer_1:
        connection: default
        exchange_options: {name: 'exchange_1', type: direct}
        queue_options:
            - {name: 'queue_1', routing_keys: ['key_1']}
            - {name: 'queue_2', routing_keys: ['key_2']}
            - {name: 'queue_n', routing_keys: ['key_n']}
```

But as far as I can tell, the bundle doesn't support any kind of configuration that binds multiple queues to one exchange under one producer.

So, my question is: is it possible to configure one producer which binds multiple queues to one exchange? Or do I have to configure one producer per queue?

Thanks very much for your help!

Ryan
