### ISSUE TITLE
Questions about deadletter queues

### ISSUE THREAD

**Issue by xleliberty** [php-amqplib/RabbitMqBundle#157]
Hi, 

I'm working on a setup where i'd like to use dead letter to delay certain works. 

I'd like to achieve something like: 

producer A  send message 
Consumer A process it and after pass it to waiting queue for x-message-ttl of 30000 ms
message is dead lettered to process B Queue
Consumer B process message that just arrived, depending of work result, it could resend message to waiting queue for another 30s round trip.

I can set this up manually in rabbitMq management console. But i can't manage to find a good configuration with the bundle.

Manually, things work when i publish a message to "Default Exchange"  but when i try it in situation, as long as i must produce messages to a named exchange instead of "default exchange" , messages are not correctly dead lettered.

Maybe someone had to deal with same kind of needs and could share experience ?

Here is my current config try.

Thanks in advance
Xavier

---

```
## order_waitcheck should send message directly into wait_checkorder and message should then been deadlettered from
# wait_checkorder to check_order 
producers:
    order_waitcheck:
        connection:       default
        exchange_options: {name: 'wait-check', type: direct}

consumers:
    ##DEAD LETTER QUEUE, WAITING FOR 30 Seconds before sending to check order immediate queue
    wait_checkorder:
        connection:     default
        callback:   trinity.amqp.blankcallback
        exchange_options: {name: 'wait-check', type: direct}
        queue_options:
            name: "wait-check-q"
            arguments: {'x-message-ttl': ['I', 30000],'x-dead-letter-exchange': ['S', 'check-orders']}
    ##Check order immediate queue
    check_order:
        connection: default
        callback: trinity.soap.sales.ordercheck.consumer
        exchange_options: {name: check-orders, type: direct}
        queue_options:
            name: 'check-orders-q'
            routing_keys:
              - 'wait-check-q'
```
