### ISSUE TITLE
Running rabbitmq:setup-fabric with RPC result in AMQPProtocolConnectionException

### ISSUE THREAD

**Issue by jamesmoey** [php-amqplib/RabbitMqBundle#160]
RabbitMQ version 3.2.3
Symfony version 2.3.*
RabbitMqBundle version 1.2.*
php-amqplib version 2.2.6

The following is my config.yml

``` yaml
old_sound_rabbit_mq:
    connections:
        default:
            host:     xxxx
            ......
            lazy:     true
    producers:
        summary_report:
            connection:       default
            exchange_options: {name: 'summary-report', type: direct}
        csv_report:
            connection:       default
            exchange_options: {name: 'csv-report', type: direct}
    consumers:
        summary_report:
            connection:       default
            exchange_options: {name: 'summary-report', type: direct}
            queue_options:    {name: 'summary-report'}
            callback:         xxx.xxx
        csv_report:
            connection:       default
            exchange_options: {name: 'csv-report', type: direct}
            queue_options:    {name: 'csv-report'}
            callback:         xxx.xxx
    rpc_clients:
        summary_sheet_store:
            connection:   default
    rpc_servers:
        summary_sheet:
            connection:   default
            callback:    xxx.xxx
```

When I run 

``` bash
app/console rabbitmq:setup-fabric
```

I get the following error on the command line.

> [PhpAmqpLib\Exception\AMQPProtocolConnectionException]
> COMMAND_INVALID - invalid exchange type ''
> Exception trace:
> () at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:432
> PhpAmqpLib\Connection\AbstractConnection->connection_close() at n/a:n/a
> call_user_func() at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:105
> PhpAmqpLib\Channel\AbstractChannel->dispatch() at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:261
> PhpAmqpLib\Channel\AbstractChannel->wait() at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:359
> PhpAmqpLib\Connection\AbstractConnection->wait_channel() at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:121
> PhpAmqpLib\Channel\AbstractChannel->next_frame() at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:229
> PhpAmqpLib\Channel\AbstractChannel->wait() at /vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:285
> PhpAmqpLib\Channel\AMQPChannel->exchange_declare() at /vendor/oldsound/rabbitmq-bundle/OldSound/RabbitMqBundle/RabbitMq/BaseAmqp.php:139
> OldSound\RabbitMqBundle\RabbitMq\BaseAmqp->exchangeDeclare() at /work/avm-webservice/vendor/oldsound/rabbitmq-bundle/OldSound/RabbitMqBundle/RabbitMq/BaseAmqp.php:167
> OldSound\RabbitMqBundle\RabbitMq\BaseAmqp->setupFabric() at /vendor/oldsound/rabbitmq-bundle/OldSound/RabbitMqBundle/Command/SetupFabricCommand.php:32
> OldSound\RabbitMqBundle\Command\SetupFabricCommand->execute() at /work/avm-webservice/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:244
> Symfony\Component\Console\Command\Command->run() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:905
> Symfony\Component\Console\Application->doRunCommand() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
> Symfony\Component\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
> Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
> Symfony\Component\Console\Application->run() at /app/console:27

The error is related to rpc_clients and rpc_servers configuration. Based on my limited understanding of Remote Procedure Call implementation in RabbitMQ, there isn't a need of exchange.
