### ISSUE TITLE
Mutiple queue not working for me

### ISSUE THREAD

**Issue by oscarjg** [php-amqplib/RabbitMqBundle#293]
I try to set multiple queue but I can't make it works. I have to implement some future post on social networks ( one for facebook, one for twitter, .... ) and I want one producer with multiple consumer each with one routing_key ( 'facebook.post', 'twitter.post', ....). When I put the message, I set the second parameter like this

``` php
$this->container->get('old_sound_rabbit_mq.social_network_producer')
            ->publish(\serialize($msg), "facebook.post")
```

``` php
$this->container->get('old_sound_rabbit_mq.social_network_producer')
            ->publish(\serialize($msg), "twitter.post")
```

but when I execute the command all message call facebook callback

```
php app/console rabbitmq:multiple-consumer -e=test -m 2 social_network --route="facebook.post"
php app/console rabbitmq:multiple-consumer -e=test -m 2 social_network --route="*facebook.post*"

```

My config looks like this:

``` yml
    producers:
        social_network:
            connection:       default
            exchange_options: {name: 'social_network', type: direct}
    multiple_consumers:
        social_network:
            connection:       default
            exchange_options: {name: 'social_network', type: direct}
            #queues_provider: cs.rabbit.provider.queue
            idle_timeout:     10
            queues:
                twitter_post:
                    name: twitter
                    callback: cs.rabbit.consumer.twitter_post
                    routing_keys:
                        - 'twitter.post'
                facebook_post:
                    name: facebook
                    callback: cs.rabbit.consumer.facebook_post
                    routing_keys:
                        - 'facebook.post'
```

What's wrong ?
