### ISSUE TITLE
Please, add an ability to bind exchange with multiple queues without defining services for each one of them.

### ISSUE THREAD

**Issue by ghost** [php-amqplib/RabbitMqBundle#321]
I want to define one publisher and one exchange of type "direct" or "topic". Then bind it with multiple queues and publicate messages based on routing key. Also i want rabbitmq:setup-fabric to work properly, so all must be done through configuration.
Queues must be durable to accumulate massages while consumers are offline.
I also do not want to define consumer services for each queue, because some of them are needed just to send deadletter to others (for delayed delivery purposes).
I suggest add "bind" option. Something like this:

``` yaml
old_sound_rabbit_mq:
    producers:
      downloader:
          connection:       default
          exchange_options: {name: downloader, type: direct}
          bind:
            - {name: downloader,  routing_keys: [downloader]}
            - :
                name: downloader.delay
                routing_keys: [downloader.delay]
                arguments:
                  x-message-ttl: [I, 3600000]
                  x-dead-letter-exchange: [S, downloader]
                  x-dead-letter-routing-key: [S, downloader]
    consumers:
        downloader:
            connection:       default
            exchange_options: {name: downloader, type: direct}
            queue_options:    {name: downloader,  routing_keys: [downloader]}
            callback:         downloader
            qos_options:      {prefetch_size: 0, prefetch_count: 1, global: false}
```

**Comment by lushc** [comment]
I've figured out a workaround for arbitrarily declaring queues that integrates with `rabbitmq:setup-fabric` without the need for a callback. It's not ideal but I just needed to ensure that a queue existed (which will be manually monitored, so no need for a consumer to be bound to it).

```yaml
consumers:
    my_consumer:
        queue_options: {name: 'my-queue', arguments: {x-dead-letter-exchange: ['S', ''], x-dead-letter-routing-key: ['S', 'my-queue.dead-letter']}}
```

I've made the assumption that my dead-letters will be sent to the default exchange, so a queue needs to exist with the same name as the `x-dead-letter-routing-key`. This is the service definition:

```yaml
AppBundle\Queue\DeclareDeadLetterQueues:
    arguments:
        $conn: '@old_sound_rabbit_mq.connection.default'
        $queues:
            - { name: 'my-queue.dead-letter' }
    tags:
        - { name: old_sound_rabbit_mq.binding }
```

And the class itself:

```php
<?php

namespace AppBundle\Queue;

use OldSound\RabbitMqBundle\RabbitMq\BaseAmqp;
use PhpAmqpLib\Channel\AMQPChannel;
use PhpAmqpLib\Connection\AbstractConnection;

class DeclareDeadLetterQueues extends BaseAmqp
{
    protected $queues;

    public function __construct(AbstractConnection $conn, ?AMQPChannel $ch = null, $consumerTag = null, array $queues)
    {
        parent::__construct($conn, $ch, $consumerTag);

        foreach ($queues as $queueOption) {
            $this->queues[] = \array_merge($this->queueOptions, $queueOption);
        }
    }

    protected function exchangeDeclare(): void
    {
        $this->exchangeDeclared = true;
    }

    protected function queueDeclare(): void
    {
        foreach ($this->queues as $queueOption) {
            $this->getChannel()->queue_declare(
                $queueOption['name'], $queueOption['passive'], $queueOption['durable'], $queueOption['exclusive'],
                $queueOption['auto_delete'], $queueOption['nowait'], $queueOption['arguments'], $queueOption['ticket']
            );
        }

        $this->queueDeclared = true;
    }
}
```
