### ISSUE TITLE
consuming routes 

### ISSUE THREAD

**Issue by datenarbeit** [php-amqplib/RabbitMqBundle#340]
Hi there, 
i am not totaly sure whats going wrong here, maybe its just my thoughts of how I things are expect to work.

i have the following config:

```
    producers:
        my_queue:
            connection:       default
            exchange_options: {name: 'myqueue', type: direct}
    consumers:
        my_queue:
            connection:       default
            exchange_options: {name: 'myqueue', type: direct}
            queue_options:
                name: 'myqueue'
                routing_keys:
                    - 'route1'
                    - 'route2'
            callback:         my_queue_callback
```

the queue is feeded like that:

```
$this->container->get('old_sound_rabbit_mq.my_queue_producer')->publish(serialize($data),'route1');
$this->container->get('old_sound_rabbit_mq.my_queue_producer')->publish(serialize($data),'route2');
```

when i now execute the consumer with the route parameter, i would actualy expect only the data from route1/route2 is consumed

```
/var/www/symfony/app/console rabbitmq:consumer  -r "route1" my_queue
/var/www/symfony/app/console rabbitmq:consumer  -r "route2" my_queue
```

but what happens is, that the consumer does not care at all about the routes. it just reads any entry from the queue, ignoring the route. when i look into the admin panel of rabbitMq I see, the the routes are created and filled (at least to me it looks like that).

so what is wrong? my config or my expectations?

best,
tom

**Comment by mrluciusfox** [comment]
Hi @datenarbeit ,
I'm having the same issue. Did you find a workaround?

**Comment by datenarbeit** [comment]
hi @mrluciusfox ,
no unfortunately not, did you?

**Comment by mrluciusfox** [comment]
Hi @datenarbeit , yes I resolved it using dynamic-consumers.
In my config.yml file I defined a dynamic-consumer like this:

```yml
dynamic_consumers:
        dispatch_sms:
            connection:       default
            exchange_options: {name: 'dispatch-sms', type: direct}
            queue_options_provider: dispatch_sms_queue_provider_service
            callback:         dispatch_sms_service
```
Note that I defined a service that implements the QueueOptionsProviderInterface, in that class you have to implement the function getQueueOptions where you can say what routing_keys you want to consume.
```php
/**
     * Return queue options
     *
     * Example:
     * array(
     *   'name' => 'example_context',
     *   'durable' => true,
     *   'routing_keys' => array('key.*')
     * )
     * @param string $context
     * @throws \Exception
     * @return array
     *
     */
    public function getQueueOptions($context = null)
    {
        return array(
            'name' => 'dispatch_sms_smsGw_'.$context,
            'durable' => true,
            'routing_keys' => array('dispatch_sms.'.$context),
            );
    }
```
The context is the extra argument that you pass to your consumer when you call it. For example:

```bash
/usr/bin/php app/console rabbitmq:dynamic-consumer -w dispatch_sms 4
```
In that case, the context that is passed to the getQueueOptions is "4", so in my getQueueOptions function I tell the consumer to consume only messages from routing_key: "dispatch_sms4".

The function getQueueOptions is writed in a class that implemented the QueueOptionsProviderInterface and is defined as a service in my service.yml file:

```yml
dispatch_sms_queue_provider_service:
      arguments: [@service_container]
      class: AppBundle\Consumer\DispatchSmsQueueOptionsProvider
```

Let me know if you need help!

Regards.
