### ISSUE TITLE
Unable to log using enable_logger: true

### ISSUE THREAD

**Issue by izeau** [php-amqplib/RabbitMqBundle#379]
Hi guys, I’ve got a complex setup with multiple queues / exchanges / consumers / producers, and I’d like to use the `enable_logger` option of RabbitMqBundle 1.10 to log consumer execution success / error / etc. However, I think I need some help on how to configure the logger.

I want the php-amqplib logs separated from my application logs, preferably in a `phpamqplib.log` rotating file. Here’s my Monolog configuration:

```yml
monolog:
    channels: ['loyalty', 'phpamqplib']
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ['!loyalty', '!phpamqplib']
        nested:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type:  console
        loyalty:
            level:    info
            type:     stream
            path:     '%kernel.logs_dir%/loyalty.log'
            channels: [loyalty]
        phpamqplib:
            type:     rotating_file
            path:     '%kernel.logs_dir%/phpamqplib.log'
            level:    debug
            channels: [phpamqplib]
```

My consumers are configured with `enable_logger: true`

```yml
old_sound_rabbit_mq:
    consumers:
        order_shipped:
            connection:       default
            exchange_options: {name: 'order_shipped_ex', type: fanout}
            queue_options:    {name: 'users_order_shipped_q'}
            callback:         app.consumer.handle_shipped_order
            enable_logger:    true
        exchange_return:
            connection:       default
            exchange_options: {name: 'exchange_return_updated_ex', type: fanout}
            queue_options:    {name: 'users_exchange_return_q'}
            callback:         app.consumer.handle_exchange_return
            enable_logger:    true
        stock_replenishment:
            connection:       default
            exchange_options: {name: 'stock_replenishment_ex', type: fanout}
            queue_options:    {name: 'stock_replenishment_q'}
            callback:         users.stock_alert.replenishment.consumer
            enable_logger:    true
```

Could you please help me out here? Thanks
