### ISSUE TITLE
Can I use this library with monolog to send logs to rabbitmq?

### ISSUE THREAD

**Issue by samusenkoiv** [php-amqplib/RabbitMqBundle#399]
I am trying to do that, there is my conf:

```
  amqp.log_channel:
    class:  PhpAmqpLib\Channel\AMQPChannel
    factory: ['@old_sound_rabbit_mq.log_producer', getChannel]
```

```
monolog:
    handlers:
        queue:
            type: amqp
            exchange: app.newsletter_manager
```

But I am getting CircularRefernceException 

> [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
>   Circular reference detected for service "monolog.handler.queue", path: "cache_warmer -> router ->
>    monolog.logger.router -> monolog.handler.queue -> app.newsletter_manager -> old_sound_rabbit_mq.
>   log_producer -> debug.event_dispatcher -> monolog.logger.event".

If I define my connection separately that would mean the application will do two connections all the time which is not acceptable.
