### ISSUE TITLE
Can't configure a dead letter queue

### ISSUE THREAD

**Issue by rifzy** [php-amqplib/RabbitMqBundle#452]
Hello

Here is my config.yml

```
producers:
        encoder:
            connection:       default
            exchange_options: {name: 'myradio-encoder', type: direct}
            service_alias:    track_encode_service
 consumers:
        dead-messages:
            connection: default
            exchange_options: {name: 'dead-messages', type: direct}
            queue_options:
                name: 'dead-messages-queue'
            callback: dead_consumer
        encoder:
            connection: default
            exchange_options: {name: 'myradio-encoder', type: direct}
            queue_options:
                name: 'encoder-response'
                arguments: {'x-dead-letter-exchange': ['S', 'dead-messages']}
            callback: encoder_consumer
            idle_timeout: false
```

My symfony app produce a rabbitmq message which is handled by a consumer (a python script)
the python script produce a response message on the same exchange (in an other queue)

this message is handled by encoder consumer using the callback EncoderConsumer
if something fails in my consumer i return a ConsumerInterface::MSG_REJECT and want in to go in my dead letter queue. The message is rejected when i return ConsumerInterface::MSG_REJECT but it don't go in the dead letters queue. Could you help me about it please ?

the dead-messages exchange exists and a dead-messages-queue is bind on this exchange
