### ISSUE TITLE
Consumer and Producer config

### ISSUE THREAD

**Issue by luxifer** [php-amqplib/RabbitMqBundle#48]
Default parameters for the consumer and the producer aren't the same. So when you don't explicitly specify all the parameters you will have tha kind of exceptions

```
PRECONDITION_FAILED - cannot redeclare exchange 'exchange-name' in vhost '/' with different type, durable, internal or autodelete value
```

with that config.yml

``` yml
old_sound_rabbit_mq:
    connections:
        default:
            host:      'localhost'
            port:      5672
            user:      'guest'
            password:  'guest'
            vhost:     '/'
    producers:
        sample_task:
            connection: default
            exchange_options: {name: 'exchange-name', type: direct}
    consumers:
        sample_task:
            connection: default
            exchange_options: {name: 'exchange-name', type: direct}
            queue_options:    {name: 'queue-name'}
            callback:         sample_task_service
```
