### ISSUE TITLE
Catching errors while using RPC

### ISSUE THREAD

**Issue by ibrahimgunduz34** [php-amqplib/RabbitMqBundle#481]
I need to catch errors, if any process failed while using RPC as parallel. It may be optional feature. So it should be able to enabled like the following, if it needed. 

```
old_sound_rabbit_mq:
    rpc_clients:
        do_foo:
            connection: default
            fail_on_error: true
```
