### ISSUE TITLE
Get callback from consumer server

### ISSUE THREAD

**Issue by manseuk** [php-amqplib/RabbitMqBundle#490]
How can i get the callback service from the consumer service ?

Example consumer config
```
upload:
  connection: default
  exchange_options: {name: upload, type: direct
  callback: upload_consumer
```
Example get consumer code 
```
$consumer = $this->getContainer()->get(
      sprintf('old_sound_rabbit_mq.%s_consumer', 'upload')
);
```
Now i want to get the service `upload_consumer` ..... how ?
