### ISSUE TITLE
multiple_consumers, same queue different routing keys, different callback

### ISSUE THREAD

**Issue by syrm** [php-amqplib/RabbitMqBundle#498]
Hello,

I don't know if this is a bug or intentional behavior this config don't work : 
```
    multiple_consumers:
        main:
            connection: default
            exchange_options: {name: global, type: topic}
            qos_options: {prefetch_count: 1}
            queues:
                amp_publish:
                    name: amp
                    callback: "articlepublish"
                    routing_keys:
                        - 'article.publish'

                amp_update:
                    name: amp
                    callback: "poc.command.amp.update"
                    routing_keys:
                        - 'article.update'
```
The last configuration "amp_update" override "amp_publish".
I made a patch to fix that, and i can do a PR, but maybe it's not a bug and it's intentional behavior. So tell me :-)
