### ISSUE TITLE
Unrecognized option "product_data" under "old_sound_rabbit_mq.connections.consumers"

### ISSUE THREAD

**Issue by ce-bo** [php-amqplib/RabbitMqBundle#510]
Hi there!

I just want to configure a simple consumer. I get this error message:
InvalidConfigurationException
Unrecognized option "product_data" under "old_sound_rabbit_mq.connections.consumers"

```yaml
old_sound_rabbit_mq:
    connections:
        default:
            url: 'localhost'
            port: 8081
            user: 'blub'
            password: 'blub'
        consumers:
            product_data:
                connection: default
                exchange_options: { name: 'product_data', type: direct }
                queue_options: { name: 'test' }
                callback: AppBundle\Consumer\ProductDataConsumer
```

Package:
php-amqplib/rabbitmq-bundle => v1.14.2
Using Symfony 3.4.0

Can anybody help, please?

Thank you!

**Comment by bmichalski** [comment]
Hi,

Your indentation seems to be incorrect, it should be:
```yaml
old_sound_rabbit_mq:
    connections:
        default:
            url: 'localhost'
            port: 8081
            user: 'blub'
            password: 'blub'
    consumers:
        product_data:
            connection: default
            exchange_options: { name: 'product_data', type: direct }
            queue_options: { name: 'test' }
            callback: AppBundle\Consumer\ProductDataConsumer
```
with `consumers` at the same the level than connections.

I hope this helps :)
