### ISSUE TITLE
Exchange names cannot contain the "period" character

### ISSUE THREAD

**Issue by psrpinto** [php-amqplib/RabbitMqBundle#60]
Messages sent to an exchange which name contains a period (.) never arrive to the RabbitMQ broker. Here's the config for such a producer:

```
producers:
    accounts_update:
        connection: default
        exchange_options: { name: 'accounts.update', type: direct }
```

According to [RabbitMQ's reference for AMQP 0-9-1](http://www.rabbitmq.com/amqp-0-9-1-reference.html#exchange.declare.exchange) periods are allowed in the exchange name:

```
The exchange name consists of a non-empty sequence of these characters: 
letters, digits, hyphen, underscore, period, or colon.
```
