### ISSUE TITLE
AMQP URL connection string breaks parse_url - Malformed parameter \"url\".

### ISSUE THREAD

**Issue by dant89** [php-amqplib/RabbitMqBundle#614]
Symfony v3.4.14
php-amqplib/rabbitmq-bundle v1.14.4

__parameters.yml__:
```
rabbit_mq_url: 'amqp://test:~t/est@rabbitmq.test.net:5672'
```

__config.yml__:
```
old_sound_rabbit_mq:
    connections:
        nca:
            url: '%rabbit_mq_url%'
            lazy: true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            use_socket: false
```

__Error__:
```
Malformed parameter \"url\".
```

Which comes from line 120 of `code/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/AMQPConnectionFactory.php`

```
$url = parse_url($parameters['url']);

if ($url === false || !isset($url['scheme']) || $url['scheme'] !== 'amqp') {
    throw new InvalidConfigurationException('Malformed parameter "url".');
}
```

parse_url does not like `amqp://test:~t/est@rabbitmq.test.net:5672` but this is a valid connection string as expected by the bundle? Do the symbols need escaping? I run into the same issue with `amqp://test:~t\/est@rabbitmq.test.net:5672`
