### ISSUE TITLE
fwrite(): send of 21 bytes failed with errno=32 Broken pipe 

### ISSUE THREAD

**Issue by GraysMile** [php-amqplib/RabbitMqBundle#617]
```
old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  pc2_inbound:
    connection: default
    queue_options:
        name: "pc2-inbound"
        durable: false
    callback: App\Consumer\InboundConsumer
```
I use this config to run command `php bin/console rabbitmq:consumer pc2_inbound`.And get error `fwrite(): send of 21 bytes failed with errno=32 Broken pipe`,how to fix it?
