### ISSUE TITLE
Queues/Messages not created automatically ?

### ISSUE THREAD

**Issue by benjamindulau** [php-amqplib/RabbitMqBundle#62]
Hi,

I have the following configuration :

``` YAML
old_sound_rabbit_mq:
    connections:
        default:
            host:      %rabbitmq.host%
            port:      %rabbitmq.port%
            user:      %rabbitmq.user%
            password:  %rabbitmq.password%
            vhost:     '/'
    producers:
        main:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
    consumers:
       post_processing:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
            queue_options:    {name: 'post_processing', durable: true}
            callback:          consumer.post_processing
        permission:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
            queue_options:    {name: 'permission', durable: true}
            callback:         consumer.permission
        index:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
            queue_options:    {name: 'index', durable: true}
            callback:         consumer.index_document
        following_encode:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
            queue_options:    {name: 'following_encode', durable: true}
            callback:         consumer.encode_following_list
        user_activity:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
            queue_options:    {name: 'user_activity', durable: true}
            callback:         consumer.user_activity
        build_feed:
            connection: default
            exchange_options: {name: 'main_direct', type: direct}
            queue_options:    {name: 'build_feed', durable: true}
            callback:         consumer.build_feed
```

And i add jobs through a manager which basically does :

``` PHP
    public function addJob($queue, $data, $priority = 0)
    {
        $message = serialize($data);
        $this->producer->publish($message, $queue);
    }
```

`$queue` being the queue name defined in the configuration.

The things is that with this configuration I have no queue nor message being added.
`sudo rabbitmqctl list_queues` returns nothing.

What am i doing wrong ?

Thanks !
