### ISSUE TITLE
Consuming multiple exchanges in MultipleConsumer

### ISSUE THREAD

**Issue by pedro-stanaka** [php-amqplib/RabbitMqBundle#633]
At my company we are heavy users of this library, but at some point we wanted to consume multiple exchanges inside one consumer and then reroute the message inside the application based on the queue name.

As of now this bundle does not support that, would that be a contribution that you would accept? I am really looking forward to get rid of my internal fork.

The idea here would be to introduce a new type of consumer, something like "UnifiedConsumer", which takes configuration from all `consumers` definitions and listen to all messages for them. And route them to the specified callbacks.

The fabric would still be setup by the consumers, but then this new consumer would consume all messages at once in a unified process.

Configuration would look like:

```yaml
old_sound_rabbit_mq:
    connections:
        default:
            lazy: true
            connection_timeout: 30
            read_write_timeout: 120
            keepalive: false
            heartbeat: 60
            use_socket: true
    consumers:
        consumer.crm.lead.event.task.executed:
            connection: default
            exchange_options:
                name: producer.crm.event.task.executed
                type: topic
            queue_options:
                name: consumer.lead.event.task.executed
                arguments:
                    x-dead-letter-exchange:
                        - S
                        - consumer.failure
                routing_keys:
                    - leadNotReached.afterTenDays
                    - noLetterOfAuthority.*
                    - signPowerOfAttorney.*
            callback: app.consumer.task_executed_event_handler
            graceful_max_execution:
                timeout: 60
                exit_code: 0
            qos_options:
                prefetch_size: 0
                prefetch_count: 2
                global: false
        consumer.crm.lead.event.contact.pushed:
            connection: default
            exchange_options:
                name: producer.lead.event.contact.pushed
                type: fanout
            queue_options:
                name: consumer.crm.lead.event.contact.pushed
                arguments:
                    x-dead-letter-exchange:
                        - S
                        - consumer.failure
            callback: app.consumer.lead_contact_pushed_event_handler
            graceful_max_execution:
                timeout: 60
                exit_code: 0
            qos_options:
                prefetch_size: 0
                prefetch_count: 2
                global: false
    ### WHAT IS NEW ###
    unified_consumer:
            connection: default
            idle_timeout: 60
            idle_timeout_exit_code: 0
            timeout_wait: 10
            qos_options:
                prefetch_size: 0
                prefetch_count: 2
                global: false
            queues:
                consumer.crm.lead.event.task.executed:
                    name: consumer.crm.lead.event.task.executed
                    callback: app.consumer.task_executed_event_handler
                    arguments:
                        x-dead-letter-exchange: [S, consumer.failure]
                    routing_keys:
                         - leadNotReached.afterTenDays
                         - noLetterOfAuthority.*
                         - signPowerOfAttorney.*
                consumer.lead.lead.command.call.enqueue:
                    name: consumer.lead.lead.command.call.enqueue
                    callback: app.consumer.call_enqueue_command_handler
                    arguments:
                        x-dead-letter-exchange: [ S, consumer.failure ]
                consumer.lead.lead.command.phone.confirm:
                    name: consumer.lead.lead.command.phone.confirm
                    callback: app.consumer.confirm_phone_command_handler
                    arguments:
                        x-dead-letter-exchange: [ S, consumer.failure ]
```

**Comment by mihaileu** [comment]
Hi, isn't it simpler to re-route the messages at rabbit level, meaning to setup [shovel](https://www.rabbitmq.com/shovel.html) or [federation](https://www.rabbitmq.com/federation.html)  ?

**Comment by pedro-stanaka** [comment]
With federation or shovel I would need to find a programatic way to describe the relationship of the queues and come up with a way to configure it outside my code. Moreover, I would lose traceability, this is what is the original queue and etc. 

Also, I have a working version of what I am mentioning here, I am just not overall happy with having to maintain a copy of this repo and rebase against it everytime there is an update. You can check the diff here: https://gist.github.com/pedro-stanaka/1e8c48d70cbc661289ed1d10441e924f

**Comment by pedro-stanaka** [comment]
Would also suffice some tip on how could I extend the bundle instead of having my own copy. I was thinking on creating another library with a custom symfony CLI command and custom consumer class, but the configuration part is kinda blocking me (as you see my old coworker changed the `OldSoundRabbitMqExtension`).

**Comment by mihaileu** [comment]
@andreea-anamaria @theodormanolescu what do you think about @pedro-stanaka proposal ?

**Comment by theodormanolescu** [comment]
There was another feature request similar to this, but it was mostly for dev environment to reduce resource usage.
Seems like a valid request but I have some questions.
I don' t understand this case:
>consume multiple exchanges inside one consumer and then reroute the message inside the application based on the queue name. 

So you want to move the routing logic inside your application?
Could you please elaborate?

**Comment by pedro-stanaka** [comment]
So, in our case we are using RabbitMQ as the broker for our Message Bus (micro-service architecture), for one single service we can have up to 80 queues, since we have a lot of different events/commands.

Whenever a event comes from lets say a exchange `command.user.create`, we have one single consumer code that will parse this message (JSON) and decode it to the proper message class and will pass it into the command bus and the proper handler then is called.

Our callback definition looks like this:

```yaml
    app.consumer.user.created:
        class: LegalOne\SymfonyWorkerToolkit\RabbitMq\Consumer\ConsumerHandler
        arguments:
            - '@annotations.cached_reader'
            - '@jms_serializer'
            - '@event_dispatcher'
            - '@command_bus'
            - '@Domain\User\Event\UserCreatedEvent' # Message class, this is how we know what we should deserialize
```
Following this logic we have one queue per message class. 

Consuming messages like this we avoid having 80*50 MB (4GB) for each instance of the service when we deploy against 1*80 MB which we have now. To worsen things we have around 40 services running each with its number of consumers (from 12 to 80).
