### ISSUE TITLE
Cosumer Argument x-single-active-consumer

### ISSUE THREAD

**Issue by kaiszy** [php-amqplib/RabbitMqBundle#678]
Hi,

i try to configure a queue as "Single Active Consumer" in Symfony like this:

```
   consumers:
        notification:
            connection: default
            exchange_options: { name: 'notification', type: direct }
            queue_options: { name: 'notification' , arguments: {'x-single-active-consumer': ['S', 'yes']} }
```
 I also try:
 
 ```
             queue_options: { name: 'notification' , arguments: {'x-single-active-consumer': ['I', 1]} }
```

But i get:

```
PRECONDITION_FAILED - invalid arg 'x-single-active-consumer' for queue 'notification' in vhost '/': {unacceptable_type,TypeISelect} 
```

How can i configure the above ?
