### ISSUE TITLE
Update documentation for Symfony 6

### ISSUE THREAD

**Issue by Axel29** [php-amqplib/RabbitMqBundle#692]
Hi,

I'm trying to implement rabbitMQ with RPC requests but the documentation seems to be madde for older versions of Symfony, especially when fetching the RpcClient in the Controller.

The documentation uses this code: `$client = $this->get('old_sound_rabbit_mq.integer_store_rpc');` but when I try this, I get the following error:

```
Service "old_sound_rabbit_mq.api_request_rpc" not found: even though it exists in the app's container, the container inside "App\Controller\ApiController" is a smaller service locator that only knows about the "doctrine", "http_kernel", "message_bus", "messenger.default_bus", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer" and "session" services. Try using dependency injection instead.
```

I tried to create a `\App\Client\ApiRequestClient` that simply extends the `\OldSound\RabbitMqBundle\RabbitMq\RpcClient` but this also throws the following Exception:

```
Cannot resolve argument $apiRequestClient of "App\Controller\ApiController::foo()": Cannot autowire service "App\Client\ApiRequestClient": argument "$conn" of method "OldSound\RabbitMqBundle\RabbitMq\BaseAmqp::__construct()" references class "PhpAmqpLib\Connection\AbstractConnection" but no such service exists. You should maybe alias this class to the existing "old_sound_rabbit_mq.connection.default" service.
```

___

Here are my files:

`config/packages/old_sound_rabbit_mq.yaml`:

```yaml
old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            use_socket: true
            lazy: true
    rpc_clients:
        api_request:
            connection: default
            unserializer: json_decode
            lazy: true
            direct_reply_to: false
            expect_serialized_response: false
    rpc_servers:
        api_request:
            connection: default
            callback: 'App\Consumer\ApiRequestConsumer'
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
            exchange_options: { name: api_request, type: topic }
            queue_options: { name: api_request_queue, durable: false, auto_delete: true }
            serializer: json_encode

```

`src/Controller/AcmeController.php`: 

```php
<?php
namespace App\Controller;

class AcmeController extends AbstractController
{
    public function foo()
    {
        $msg    = [
            'foo' => 'Foo value',
            'bar' => 'Bar value',
        ];

        $client = $this->get('old_sound_rabbit_mq.integer_store_rpc');
        $client->addRequest(json_encode($msg), 'api_request', 'acmeRoute');

        try {
            $replies = $client->getReplies();
        } catch (\PhpAmqpLib\Exception\AMQPTimeoutException $e) {
            // Silence is golden
        }
    }
}

```

`src/Consumer/ApiRequestConsumer.php`:

```php
<?php
namespace App\Consumer;

use OldSound\RabbitMqBundle\RabbitMq\ConsumerInterface;
use PhpAmqpLib\Message\AMQPMessage;

class ApiRequestConsumer implements ConsumerInterface
{
    public function execute(AMQPMessage $msg)
    {
        return ['success' => true, 'message' => 'RPC request complete!'];
    }
}

```

___

Thanks for your help.
