### ISSUE TITLE
Message rates stop at 25 msg/s

### ISSUE THREAD

**Issue by sliver** [php-amqplib/RabbitMqBundle#7]
I have a simple command 

config.yml:

```
producers:
    my-producer':
        connection: default
        exchange_options: {name: 'my-producer', type: direct}
```

SimpleCommand.php

```
    ...
    $producer = $this->getContainer()
            ->get('old_sound_rabbit_mq.my-producer');

    for($i = 0; $i < 10000; $i++) {
        $producer->publish('for_test');
    }
    ...
```

It runs correctly but the message rates display on the RabbitMq management  is alway 25 msg/s.
Run 2 process at the same time can get 50 msg/s.

At the same machine, I can get about 2000 msg/s using node-amqp.
Do I miss something?

debian 6
symfony 2.0.3
rabbitmq-server version 2.6.1 / R14A
